cask_args appdir: "~/Applications"
tap "homebrew/cask"
tap "derailed/k9s"
tap "lucagrulla/tap"
tap "warrensbox/tap"
brew "aws-iam-authenticator"
brew "cw"
brew "derailed/k9s/k9s"
brew "gnu-sed"
brew "jq"
brew "kubernetes-cli"
brew "stern"
brew "warrensbox/tap/tfswitch"
cask "rectangle"
cask "iterm2"
cask "visual-studio-code"
